# Generated by Django 5.1.6 on 2025-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('students_enrolled', models.IntegerField(default=0)),
            ],
        ),
    ]
