# Generated by Django 5.1.6 on 2025-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
