# Generated by Django 5.1.6 on 2025-04-19 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0009_eventtwo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtwo',
            name='location',
            field=models.CharField(default='Virtual', max_length=200),
        ),
        migrations.AddField(
            model_name='eventtwo',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_events_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
